

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
  DisplayCopNames: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  CountComments: false
  Max: 30

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enable: false

Style/WhileUntilModifier:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: false



#以下導入時記載内容。inherit_gem: { rubocop-rails-omakase: rubocop.yml }のみ元々コメントアウトなし
# Omakase Ruby styling for Rails
#inherit_gem: { rubocop-rails-omakase: rubocop.yml }
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
