development:
  adapter: async

test:
  adapter: test

# 本番環境の接続先を変更。appのDBを使用するため、公式に記載がある通りconnect_to以下は記載せず。
production:
  adapter: solid_cable
  polling_interval: 0.1seconds
  message_retention: myapp_production
