ja:
  header:
    top: TOP画面へ
    login: ログイン
    logout: ログアウト
    new_user: 新規登録
    rackets_index: ラケット投稿一覧
  rackets:
    create:
      success: ラケットの投稿に成功しました
      failure: ラケットの投稿に失敗しました
    update:
      success: ラケットの情報の更新に成功しました
      failure: ラケットの投稿に失敗しました
    destroy:
      success: 投稿したラケット情報を削除しました
  profiles:
    create:
      success: プロフィールの作成に成功しました
      failure: プロフィールの作成に失敗しました
    update:
      success: プロフィール情報の更新に成功しました
      failure: プロフィール情報の更新に失敗しました
